### PR TITLE
Adds documentation for Workspaces

### PR DESCRIPTION
**Pull request by OwenMatsuda**
This PR adds documentation for Dash Enterprise Workspaces.

Post-merge checklist:

The master branch is auto-deployed to `dash.plotly.com`.
Once you have merged your PR, wait 5-10 minutes and check dash.plotly.com
to verify that your changes have been made.

- [x] I understand

### CODE REVIEW

**Comment by chriddyp** [comment]
@OwenMatsuda Let's add this to https://github.com/plotly/dash-enterprise-docs/ instead as it will be a top-level item rather than a subchapter of app manager

**Comment by OwenMatsuda** [comment]
I put it in here to be used by https://github.com/plotly/dash-enterprise-docs/pull/283. It seemed like the convention, but I could be wrong. I just guessed off of the code since it wasn't really documented.

**Comment by gzork** [comment]
@chriddyp please correct me if I'm wrong, but @OwenMatsuda my understanding is these docs don't need to be added to the OSS dash docs too, so this PR is not needed I think.

**Comment by OwenMatsuda** [comment]
Ohh I see those were just the docs used both in open source and enterprise. Got it.

**Comment by chriddyp** [comment]
That's correct 👍

**Pull request closed without merging**
