### PR TITLE
Update dash-cytoscape requirements to v0.1.1

### PR DESCRIPTION
**Pull request by xhlulu**
Let's see if this might solve some of the problems associated with the snippets.

Post-merge checklist:

The master branch is auto-deployed to `dash.plotly.com`.
Once you have merged your PR, wait 5-10 minutes and check dash.plotly.com
to verify that your changes have been made.

- [ ] I understand

If this PR documents a new feature of Dash:

- [ ] Comment on the original Dash issue with a link to the new docs.
- [ ] Reply to any community thread(s) asking for this feature.

If this PR includes a new dataset available at a remote URL:
- [ ] I have added this dataset to the `datasets/` folder
- [ ] I have added a mapping between the remote URL and the filename in the
`datasets/` folder into the `find_and_replace` dict in `dash_docs/tools.py`

If this PR adds an image or animated GIF:
- [ ] This image was saved and referenced locally rather than via an external link

If I introduced a new relative link inside `dcc.Markdown`:
- [ ] I considered whether I could replace the `dcc.Markdown` call with `rc.Markdown`, which will replace relative links with `tools.relpath` internally. Otherwise, I used e.g. `<dccLink href=tools.relpath('/layout') children="the first chapter"/>` instead of `[the first chapter](/layout)` (importing `tools` from `dash_docs`), and set `dangerously_allow_html=true` in the `dcc.Markdown` call.

If I changed the `chapter_index` by removing or relocating a page:
- [ ] I added a redirect in `dash_docs/server.py` from the old URL to the new URL

### CODE REVIEW

**Comment by alexcjohnson** [comment]
@xhlulu the test failure looks like a real py2 syntax issue?

```
    from .Tree import Tree
E     File "/home/circleci/project/venv/lib/python2.7/site-packages/dash_cytoscape/utils/Tree.py", line 85
E       **self.edge_data
E        ^
E   SyntaxError: invalid syntax
```

**Comment by rpkyle** [comment]
> @xhlulu the test failure looks like a real py2 syntax issue?
> 
> ```
>     from .Tree import Tree
> E     File "/home/circleci/project/venv/lib/python2.7/site-packages/dash_cytoscape/utils/Tree.py", line 85
> E       **self.edge_data
> E        ^
> E   SyntaxError: invalid syntax
> ```

Appears potentially related to (closed) https://github.com/plotly/dash-cytoscape/issues/60. I recall talking with @Marc-Andre-Rivet about this last fall, at the time I wasn't able to build `dash-cytoscape` with py27 at all. 

Might help to require py3+  explicitly, unless we want to modify the package so that py2.7 is supported too.

**Comment by xhlulu** [comment]
I'm not against explicitly requiring python 3, but i think it's a conversation we should have for a new release. As for this, is there something in the code i could change to make the tests pass?

**Comment by alexcjohnson** [comment]
@xhlulu the PR here is updating the version to v0.1.1, but you've got a PR from over a year ago https://github.com/plotly/dash-cytoscape/pull/53 that fixes this issue, saying:
> v0.1.1 broke compatibility with Python 2. Therefore, modified code to be compatible with Python 2.

Seems like there have been no new releases since then? Looks like only [bugfixes and non-code changes since](https://github.com/plotly/dash-cytoscape/compare/v0.1.1...master) so can we make a v0.1.2? There are a bunch of open PRs that would be nice to get into a v0.2 but they may take some time to finish, in the meantime it would be nice to get all the tweaks in the last year released.

**Comment by xhlulu** [comment]
v0.2.0 is going to be released, I don't think this PR is any useful anymore since it's outdated anyway.

**Pull request closed without merging**
