### PR TITLE
Update docker image version in R deployment docs

### PR DESCRIPTION
**Pull request by joelostblom**
The current image (3.6.2) fails to build, and the new one was updated 3 months ago I also removed some whitespaces that make it hard to copy paste form the docs.

Post-merge checklist:

The master branch is auto-deployed to `dash.plotly.com`.
Once you have merged your PR, wait 5-10 minutes and check dash.plotly.com
to verify that your changes have been made.

- [x] I understand

### CODE REVIEW

**Comment by jdamiba** [comment]
@rpkyle This change looks good to me, what do you think?

**Review by rpkyle — APPROVED** [review]
@jdamiba Agreed! I just double-checked the tags [here](https://hub.docker.com/r/plotly/heroku-docker-r/tags?page=1&ordering=last_updated) to confirm.

@joelostblom Thanks for the fix! :woman_dancing: :bow:

**Comment by joelostblom** [comment]
Just a heads up that that I do not see these changes live at https://dashr-docs.herokuapp.com/deployment, which I believe I should according to the Post merge checklist in the PR template?

**Comment by rpkyle** [comment]
> Just a heads up that that I do not see these changes live at https://dashr-docs.herokuapp.com/deployment, which I believe I should according to the Post merge checklist in the PR template?

Hi @joelostblom, we'll need to redeploy the Dash for R documentation for the changes to appear, I'll try to do that tonight or tomorrow.

**Comment by rpkyle** [comment]
> Just a heads up that that I do not see these changes live at https://dashr-docs.herokuapp.com/deployment, which I believe I should according to the Post merge checklist in the PR template?

@joelostblom OK! I've redeployed the docs, your changes are now live. :rocket:

**Comment by joelostblom** [comment]
Thanks for letting me know!

**Pull request merged**
