### PR TITLE
Offline assets

### PR DESCRIPTION
**Pull request by wbrgss**
Making the docs compatible offline, ideally with zero (0) network requests.

TODO:

~[ ] find an alternative to the calls to https://ghbtns.com/ for the "Star" buttons. We could just  replace the iframes with a static image and a link to the repo. We could also introduce logic for checking if the machine is offline but...that's going to make a network request and kind of make the point moot~

~[ ] Find an alternative to the embedded Codepen request on the "Multi Page Apps" chapter (`dash_docs/tutorial/urls.py``)~

<hr><hr>

Post-merge checklist:

The master branch is auto-deployed to `dash.plot.ly`.
Once you have merged your PR, wait 5-10 minutes and check dash.plot.ly
to verify that your changes have been made.

- [x] I understand

If this PR documents a new feature of Dash:

- [ ] Comment on the original Dash issue with a link to the new docs.
- [ ] Reply to any community thread(s) asking for this feature.

If this PR includes a new dataset available at a remote URL:
- [ ] I have added this dataset to the `datasets/` folder
- [ ] I have added a mapping between the remote URL and the filename in the
`datasets/` folder into the `find_and_replace` dict in `dash_docs/tools.py`

If I introduced a new relative link inside `dcc.Markdown`:
- [ ] I used e.g. `<dccLink href="/getting-started" children="the first chapter"/>` instead of `[the first chapter](/getting-started)`.

### CODE REVIEW

**Comment by chriddyp** [comment]
💃 

could you also update the `PR_CHECKLIST` to include a checklist item about "If I added an image, this image was saved and referenced locally rather than via an external link"

**Comment by wbrgss** [comment]
Thanks for taking a look @chriddyp. Good idea re: the PR template; I think this should also be replaced because we now recommend using `reusable_components.Markdown` which uses `tools.relpath` internally (in this PR I broke out `html.Img()`s because I was ignorant of this:

>  I used e.g. <dccLink href="/getting-started" children="the first chapter"/> instead of [the first chapter](/getting-started).

Note that @markzporter will be making a similar PR (we split up this task)

**Comment by wbrgss** [comment]
Also, @chriddyp (or @Marc-Andre-Rivet) do you have an opinion on the external requests above in my `TODO` (edited opening comment)? These external requests will not break the app by any means but still may trigger a network request audit/script for airgapped environments.

**Comment by chriddyp** [comment]
I think it's fine if a request is triggered as long as it doesn't break the app.

**Comment by Marc-Andre-Rivet** [comment]
image
Looks like flakiness - py36 and 37 passed, rerunning.

**Comment by Marc-Andre-Rivet** [comment]
There's many requests for `https://codepen.io/chriddyp/pen/bWLwgP.css` in the docs, do we care about those?

**Comment by wbrgss** [comment]
> There's many requests for https://codepen.io/chriddyp/pen/bWLwgP.css in the docs, do we care about those?

The docs look OK without wifi, presumably without this CSS. So I say it's OK given https://github.com/plotly/dash-docs/pull/783#issuecomment-587122275. No strong opinions though.

**Pull request merged**
