### PR TITLE
Render as 15px to fix wavy text

### PR DESCRIPTION
**Pull request by chriddyp**
Hopefully fixes the issues windows users are seeing with e.g.
image

cc @jdamiba @VeraZab

### CODE REVIEW

**Comment by VeraZab** [comment]
A comparison here, if you look at the word 'virtualization' for ex, 15px and 14px do look better imo:

16px:
Screen Shot 2020-04-20 at 11 52 21 AM
15px:
Screen Shot 2020-04-20 at 11 53 16 AM
14px:
Screen Shot 2020-04-20 at 11 53 50 AM
17px:
Screen Shot 2020-04-20 at 11 54 32 AM

**Comment by alexcjohnson** [comment]
Is this just an empirical observation or do we have some understanding of why this would matter? Will these users have problems again if they change page zoom?

I also notice that capitalization is inconsistent, any chance that matters to Windows but not elsewhere, so we're actually falling back on a system file or something rather than the typekit file we intended?

```
~/plotly/dash-docs/dash_docs/assets> ag campaign *.css
override.css
7:  font-family: "Campaign", serif;

typography.css
7: * campaign:
36:font-family:"campaign";
42:font-family:"campaign";
48:font-family:"campaign";
54:font-family:"campaign";
60:font-family:"campaign";
66:.tk-campaign { font-family: "campaign",sans-serif; }
`

**Comment by VeraZab** [comment]
oh good catch for the capitalization we should keep it consistent, and the serif, sans-serif rule too.. 
For the zoom, I've actually observed letters looking better, not worst when zoomed in, commented about it [here](https://github.com/plotly/marketing-website/issues/313#issuecomment-611235331)

**Comment by chriddyp** [comment]
> we should keep it consistent, and the serif, sans-serif rule too..

I don't follow here, what does 'keep it consistent' mean?

**Comment by VeraZab** [comment]
this is the right rule: font-family: "campaign",sans-serif;

**Comment by chriddyp** [comment]
Got it, thanks. I updated the fallback for both fonts 👍

**Pull request merged**
