### PR TITLE
[WIP] add more comprehensive performance section skeleton

### PR DESCRIPTION
**Pull request by michaelbabyn**
This PR will update the performance section to be more comprehensive as per https://github.com/plotly/dash-enterprise-docs/issues/140. 

Post-merge checklist:

The master branch is auto-deployed to `dash.plot.ly`.
Once you have merged your PR, wait 5-10 minutes and check dash.plot.ly
to verify that your changes have been made.

- [ ] I understand

If this PR documents a new feature of Dash:

- [ ] Comment on the original Dash issue with a link to the new docs.
- [ ] Reply to any community thread(s) asking for this feature.

If this PR includes a new dataset available at a remote URL:
- [ ] I have added this dataset to the `datasets/` folder
- [ ] I have added a mapping between the remote URL and the filename in the
`datasets/` folder into the `find_and_replace` dict in `dash_docs/tools.py`

If I introduced a new relative link inside `dcc.Markdown`:
- [ ] I used e.g. `<dccLink href="/getting-started" children="the first chapter"/>` instead of `[the first chapter](/getting-started)`.

### CODE REVIEW

**Comment by chriddyp** [comment]
very nice 😸

**Comment by jackparmer** [comment]
I get questions all the time along the lines of, "How do I make this Dash app faster?"
Do we have any current links for this? Would be nice to include all the usual suspects as well as Dash Enterprise features:
- Datashader, WebGL, and Dask for "big data"
- Redis caching on Dash Enterprise
- Dash Enterprise Kubernetes for high traffic Dash apps
- Memoization
- Advanced workarounds and Dash WIPs such as Arrow serialization: https://github.com/plotly/dash/issues/290

**Comment by jackparmer** [comment]
Ah, I'm sorry, this page exists - https://dash.plotly.com/performance
Would be nice to include some Dash Enterprise stuff in here at the bottom

**Comment by alexcjohnson** [comment]
stale

**Pull request closed without merging**
