### PR TITLE
update normalized redirects

### PR DESCRIPTION
**Pull request by chriddyp**
Post-merge checklist:

The master branch is auto-deployed to `dash.plot.ly`.
Once you have merged your PR, wait 5-10 minutes and check dash.plot.ly 
to verify that your changes have been made.

- [ ] I understand

If this PR documents a new feature of Dash:

- [ ] Comment on the original Dash issue with a link to the new docs.
- [ ] Reply to any community thread(s) asking for this feature.

### CODE REVIEW

**Comment by chriddyp** [comment]
Based off of https://github.com/plotly/dash-docs/pull/707/files.

I don't think we need to put in a redirect for `/faqs` since that was just a broken link

**Comment by chriddyp** [comment]
(rather than a valid link that changed)

**Comment by alexcjohnson** [comment]
Good call, thanks @chriddyp!

Also `/dash-core-components/logout_button` -> `/dash-core-components/logoutbutton`

I wouldn't mind including `/faq` as a redirect, as that's probably what I'd type if I tried to enter this URL manually... but you're right, just a typo so not a big deal.

**Comment by alexcjohnson** [comment]
BTW is it intentional to use `302` rather than `301` as the redirect code? Permanent `301` seems more semantically correct but I don't know if there are other considerations.

**Comment by chriddyp** [comment]
yeah it should be a permanent one, i think that's just a typo that got repeated

**Comment by chriddyp** [comment]
Huh, getting a percy issue in the tests?
```
        new_retry = self.new(
            total=total,
            connect=connect, read=read, redirect=redirect, status=status_count,
            history=history)
    
        if new_retry.is_exhausted():
>           raise MaxRetryError(_pool, url, error or ResponseError(cause))
E           urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='percy.io', port=443): Max retries exceeded with url: /api/v1/builds/ (Caused by ResponseError('too many 503 error responses'))
```

**Pull request merged**
