### PR TITLE
Prep work to copy latest doc improvements over into Dash Enterprise 4.1.0's release

### PR DESCRIPTION
**Pull request by chriddyp**
See https://github.com/plotly/dash-enterprise-docs/pull/709 for context.

Post-merge checklist:

The master branch is auto-deployed to `dash.plotly.com`.
Once you have merged your PR, wait 5-10 minutes and check dash.plotly.com
to verify that your changes have been made.

- [ ] I understand

If this PR documents a new feature of Dash:

- [ ] Comment on the original Dash issue with a link to the new docs.
- [ ] Reply to any community thread(s) asking for this feature.

If this PR includes a new dataset available at a remote URL:
- [ ] I have added this dataset to the `datasets/` folder
- [ ] I have added a mapping between the remote URL and the filename in the
`datasets/` folder into the `find_and_replace` dict in `dash_docs/tools.py`

If this PR adds an image or animated GIF:
- [ ] This image was saved and referenced locally rather than via an external link

If I introduced a new relative link inside `dcc.Markdown`:
- [ ] I considered whether I could replace the `dcc.Markdown` call with `rc.Markdown`, which will replace relative links with `tools.relpath` internally. Otherwise, I used e.g. `<dccLink href=tools.relpath('/layout') children="the first chapter"/>` instead of `[the first chapter](/layout)` (importing `tools` from `dash_docs`), and set `dangerously_allow_html=true` in the `dcc.Markdown` call.

If I changed the `chapter_index` by removing or relocating a page:
- [ ] I added a redirect in `dash_docs/server.py` from the old URL to the new URL

### CODE REVIEW

**Comment by jdamiba** [comment]
@VeraZab Can you please review this? I updated the tarball to include https://github.com/plotly/dash-docs/pull/1069 and https://github.com/plotly/dash-docs/pull/1072, which were merged to master after this branch was opened. 

I also made some changes to ensure this passes CI: added the `future-fstrings` package to make sure that the use of string interpolation in https://github.com/plotly/dash-docs/pull/1071/files#diff-4bf4f77d0b44135aa91f2ea268cfebaf5a6e8ec2d4f977ad0ee33b6eb6dfb192 doesn't break the Python 2.7 CI build and updated the sitemap as well.

**Comment by VeraZab** [comment]
Ok, so let's rebase this pr from master please. 
And 💃 !

**Comment by VeraZab** [comment]
When it's merged, we're going to create a release bundle and tag, and publish it in the repo. It's this release bundle that we're going to port over to dash-enterprise-docs, do another final check, then the dash-enterprise-docs pr could be merged

**Review by VeraZab — APPROVED** [review]
can merge after rebase

**Comment by VeraZab** [comment]
@chriddyp is it python setup.py that creates the bundle? could you point us to the right command here please.

**Pull request merged**
