### PR TITLE
Update markdown for store example accordingly to #493

### PR DESCRIPTION
**Pull request by StefanTippelt**
Post-merge checklist:

The master branch is auto-deployed to `dash.plot.ly`.
Once you have merged your PR, wait 5-10 minutes and check dash.plot.ly 
to verify that your changes have been made.

- [x] I understand

### CODE REVIEW

**Comment by alexcjohnson** [comment]
Ah thanks! But this begs the question, why doesn't this part use the pattern elsewhere of generating the syntax block from the same example file?

https://github.com/plotly/dash-docs/blob/eaa0cbe97bcf3614137013d198a683ff8c6cea20/tutorial/core_component_examples.py#L1218-L1219

Probably the answer is just that we wrote this example before we thought of `tools.load_example`, but @StefanTippelt would you like to have a go of getting rid of this duplication?

**Comment by StefanTippelt** [comment]
Thanks @alexcjohnson for the hint, I updated it accordingly.

**Comment by alexcjohnson** [comment]
@StefanTippelt apologies for letting this one slip through. I see what was going on, `Store` components need to be in the layout from the beginning, so the actual executed code needs to not have these, but the syntax needs them or it won't make sense. I'm going to close this PR and clean this up in a new PR. Thanks for the original fix #493 and for pointing out this follow-on!

**Comment by StefanTippelt** [comment]
Thanks @alexcjohnson for the follow up!

**Pull request closed without merging**
