### PR TITLE
Use prerelease 0.23.1rc1 to test out Link component

### PR DESCRIPTION
**Pull request by valentijnnieman**
@chriddyp Let's test out that Link component :-)

### CODE REVIEW

**Comment by valentijnnieman** [comment]
These tests are failing too - could it be related to https://github.com/plotly/dash-core-components/pull/224 ?

**Comment by chriddyp** [comment]
i just redeployed the test app, it's available here:  https://dash-docs-pr-111.herokuapp.com/

**Comment by chriddyp** [comment]
I'm looking into the tests now.

**Comment by chriddyp** [comment]
Hm, tests are passing locally.
```
python -m unittest tests.test_integration.Tests
.......
Ran 1 test in 170.539s

OK
```

It must just be some timeout.

**Comment by chriddyp** [comment]
OK, rebuilding works, so it looks like this wasn't an issue with the code, just a timeout issue.

Of course, we should try to make this less susceptible to timeouts :)

**Pull request closed without merging**
