### PR TITLE
added layout animation in example

### PR DESCRIPTION
**Pull request by emmanuelle**
Post-merge checklist:

The master branch is auto-deployed to `dash.plot.ly`.
Once you have merged your PR, wait 5-10 minutes and check dash.plot.ly 
to verify that your changes have been made.

- [x] I understand

### CODE REVIEW

**Comment by emmanuelle** [comment]
I don't understand the CI fail for python 2.7. Seems to be related to snapshots. Could the transitions prevent the snapshots from behaving correctly? (are they tested only for python 2??)

**Comment by alexcjohnson** [comment]
I doubt it has anything to do with transitions, probably just a spurious error (perhaps related to https://github.com/plotly/dash/pull/1001) but then looks like you tried to rerun the same test - which percy isn't very good at unless you wait a very long time. Better to push a new dummy commit if you want to rerun the test. Or just wait until https://github.com/plotly/dash/pull/1001 is included in a release (related: https://github.com/plotly/dash-docs/pull/690) and try again at that point.

**Comment by nicolaskruchten** [comment]
Hmm I think you'll need to hardcode the x and y ranges and set the transition order to be 'traces first' or something to avoid the "smooth layout transition/rough data transition" effect that we're seeing here

**Comment by emmanuelle** [comment]
The percy comes from the added code + explanation. I'll let the reviewer accept the percy diff. @nicolaskruchten @alexcjohnson (and thanks for your help).

**Pull request merged**
