### PR TITLE
Remove meta tags to remove SEO.

### PR DESCRIPTION
**Pull request by shammamah**

### CODE REVIEW

**Comment by jackparmer** [comment]
This is only for the alternate docs URL, correct? Official primary docs URL still needs to have these 

Envoyé de mon iPhone

**Comment by shammamah** [comment]
@jackparmer Yes, this branch will not be merged into `master` and will be the branch from which we deploy to the alternate URL.

**Comment by chriddyp** [comment]
there should also be the `noindex` tag: https://support.google.com/webmasters/answer/93710?hl=en

**Comment by alexcjohnson** [comment]
@shammamah is this PR still relevant?

**Comment by shammamah** [comment]
Nope! I'll close it right now.

**Pull request closed without merging**
