### PR TITLE
DataTable Tooltips

### PR DESCRIPTION
**Pull request by Marc-Andre-Rivet**
Follow up to https://github.com/plotly/dash-table/pull/831.
Related to https://github.com/plotly/dash-table/issues/295

Waiting for https://github.com/plotly/dash-docs/pull/1008 to be merged in first.

### CODE REVIEW

**Comment by chriddyp** [comment]
Alright, I just reworked this a bit. A couple of examples aren't working for though:
1. Tables within tooltips - the tooltip isn't appearing
2. `css=` property to specify tooltip styles - the tooltips aren't styled

@Marc-Andre-Rivet - Could you take a look and fix up as necessary?

Otherwise I think we're good 💃

**Review by rpkyle — APPROVED** [review]
:woman_dancing:

**Comment by Marc-Andre-Rivet** [comment]
@chriddyp The tooltip nested tables look like a `tooltip` / `columns` misalignment 
https://github.com/plotly/dash-docs/pull/1001/commits/38d01a54a93caf51332c4a40d899f5e64f3d2f81 should fix it

**Comment by Marc-Andre-Rivet** [comment]
@chriddyp Forgot about the `dash-tooltip` vs. `dash-table-tooltip` distinction. The former is the container and the other is for the content. Sadly not super clean naming convention, but it achieves the desired result. https://github.com/plotly/dash-docs/pull/1001/commits/bc313ad468cc8c7ac0cb6fb3317a41d5e9c4ccee

**Pull request merged**
