### PR TITLE
Update object detection app screencast

### PR DESCRIPTION
**Pull request by ycaokris**
- [x] Deployed on gallery 
- Update screencast on https://dash.plot.ly/gallery template

### CODE REVIEW

**Comment by byronz** [comment]
for binaries files, make sure you use `lfs`
https://help.github.com/en/articles/configuring-git-large-file-storage

**Comment by shammamah** [comment]
Other than what @byronz mentioned, looks good to me :) One redesign down, [large number] to go! 💃

**Comment by ycaokris** [comment]
@byron please review..

**Comment by chriddyp** [comment]
We should avoid displaying 2MB files on the web page as it take a really long time to load, especially on mobile. Could we use a video instead with the `html.Video` component? Here's a code snippet I used in a previous project:
```
    html.Video(style={'width': '100%'}, controls=True, children=[
        html.Source(src='/assets/my-video.mp4', type='video/mp4'),
        html.P([
            "Your browser doesn't support HTML5 video. Here is a ",
            html.A('link to the video', href='/assets/my-video.mp4'),
            'instead.'
        ])
]),
```

**Comment by ycaokris** [comment]
> We should avoid displaying 2MB files on the web page as it take a really long time to load, especially on mobile. Could we use a video instead with the `html.Video` component? Here's a code snippet I used in a previous project:
> 
> ```
>     html.Video(style={'width': '100%'}, controls=True, children=[
>         html.Source(src='/assets/my-video.mp4', type='video/mp4'),
>         html.P([
>             "Your browser doesn't support HTML5 video. Here is a ",
>             html.A('link to the video', href='/assets/my-video.mp4'),
>             'instead.'
>         ])
> ]),
> ```

That could work, though I assume mp4 is usually much more larger than .gif and may slows down commands like git clone. IMO most screencasts in gif could be confined below 2~3MB, without affecting visual display. The only two .gif I've noticed as really large in /assets/images/gallery for now comes from Vanguard (9.9MB) and drug discovery (8.1MB)

**Comment by chriddyp** [comment]
>  though I assume mp4 is usually much more larger than .gif 

I was able to save a high quality 58 second MP4 in just 1MB in another project

**Comment by ycaokris** [comment]
In the most two recent builds (#994, #995 on https://percy.io/plotly/dash-docs),  a javascript loading message start showing up on page loading. 
This was captured by Percy snapshots, raises a difference alert on each page, and affects every subsequent builds. (https://percy.io/plotly/dash-docs/builds/1548700). 

image

Loading after cache clearing: 
ezgif com-video-to-gif (3)


Abnormal page loading(build #994) appears after my most recent commit in this PR:
- [Resize to smaller screencast](https://github.com/plotly/dash-docs/pull/433/commits/2b735773bf29d79708c3375cc5533911cf1e00cd)

And builds(#993) seems normal upon previous commit:  
-  [Revert "Add git lfs to large gif](https://github.com/plotly/dash-docs/pull/433/commits/d5d359219c15a4422c26885a00ddc37d47e299b4)

I'm not sure what is the cause.  @chriddyp would you please have a look if possible?

**Comment by ycaokris** [comment]
The above issue has been solved by updating GTM, verified with no pardot showing up in in build #998.

**Pull request merged**
