### PR TITLE
Use dcc.Link in markdown sections for faster navigation

### PR DESCRIPTION
**Pull request by chriddyp**
The regex, FWIW:
`\[([\w\s]+)\]\(\/([\w\s\-\_\/]+)\)`

replaced with: `<dccLink href="/$2" children="$1"/>`

across `*.py`

### CODE REVIEW

**Comment by chriddyp** [comment]
I'd like to get this one in today so that I can create a new build for DE

**Comment by Marc-Andre-Rivet** [comment]
Something changed about how the html components docs gets rendered:
image

**Comment by Marc-Andre-Rivet** [comment]
Some more diffs in the component descriptions
image

`<form>` is missing

**Comment by Marc-Andre-Rivet** [comment]
`<template> -> `<template\>`
image

**Comment by Marc-Andre-Rivet** [comment]
Dash Persistance
image

**Comment by Marc-Andre-Rivet** [comment]
html.Canvas, a subtle one
image

**Comment by Marc-Andre-Rivet** [comment]
Advanced Git
image

**Comment by Marc-Andre-Rivet** [comment]
React for Python Devs `<h1\>`
image

**Comment by Marc-Andre-Rivet** [comment]
Graduated Bar Examples and Reference
image

**Comment by Marc-Andre-Rivet** [comment]
Dash HTML Components main page
image

**Comment by Marc-Andre-Rivet** [comment]
dcc.Graph
image

**Comment by Marc-Andre-Rivet** [comment]
External resources
image
image

**Comment by Marc-Andre-Rivet** [comment]
DAQ Gauge
image

**Comment by chriddyp** [comment]
My goodness, that took longer and was more complex than I thought it would be. All of the final percy screenshots are OK now. Looking for a 💃

**Pull request merged**
