### PR TITLE
Bump version to dash==1.0.2

### LINKED ISSUE #602: Update dash to 1.0.2

### PR DESCRIPTION
**Pull request by Marc-Andre-Rivet**
Fixes #602 

Post-merge checklist:

The master branch is auto-deployed to `dash.plot.ly`.
Once you have merged your PR, wait 5-10 minutes and check dash.plot.ly 
to verify that your changes have been made.

- [x] I understand

### CODE REVIEW

**Comment by chriddyp** [comment]
Re visual changes, might want to confirm that the default example indeed "expands to the width of its container."
image

**Comment by chriddyp** [comment]
Probably a separate issue, but looks like this example doesn't render.
image

**Comment by chriddyp** [comment]
Also probably another separate issue, but this example doesn't have a scrollbar like it says it should:
image

**Comment by Marc-Andre-Rivet** [comment]
For a minute or two it was still pointing to dash==1.0.1, I think that explains the first screenshot

image

2nd one
image

The 3rd one I don't see the scroll either. Checking.

**Pull request merged**
