### PR TITLE
Update tabs section

### LINKED ISSUE #173: Update Tabs docs
We've merged some PR's that contain fixes for the Tabs component, notably bugs that we mention in the docs. We should update the docs section about Tabs!

### PR DESCRIPTION
**Pull request by valentijnnieman**
This updates `dash-core-components` to the latest version, which includes fixes for bugs in the Tabs component, that are mentioned in the docs. It also removes those mentions, since the bugs should be fixed in this release. Closes #173

### CODE REVIEW

**Comment by valentijnnieman** [comment]
@chriddyp I've added 3 examples on how to style Tabs, as per #127. Could you rereview? Thanks!

**Comment by chriddyp** [comment]
Looks good! A couple suggestions:
- [ ] Can we include what the stylesheet looks like for the first example? You could include another code block above or below the python example. Above the css code, indicate the name of the file like *`asssets/tabs.css`* and also mention that you should 
```
Save the file in an `assets` folder (it can be named anything you want). Dash will automatically include this CSS when the app is loaded ([learn more about including CSS in your app](/external-resources)
```
image

- Could we do another example that includes really long tab names? This actually comes up a lot and I'd like to have a recipe handy for it. The difficulty with the CSS is figuring out how to have the tabs all the same height when one tab overflows to two lines and the other tab stays on one line. Here's a good example: https://dash-intro-presentation.herokuapp.com/dash/presentation/

- For the shorter tab example, is there any way to get the bottom border line to extend to the entire container? Similar to GitHub
image
image

- Could we replace the second example (the circular buttons) with one like this? 
image

- Finally, since this page is getting long, could we add a sort table of contents at the top? Similar to what we have here: https://dash.plot.ly/external-resources

**Comment by chriddyp** [comment]
Another nice CSS example might be how to do multi-line tabs when you have many tabs. For example, here's the settings page from gmail - if there isn't enough space, the tabs move on to 2 or 3 lines:
image
image

**Comment by valentijnnieman** [comment]
@chriddyp Alright, updated the existing examples a bit. Want to re-review?

**Comment by chriddyp** [comment]
Looking at the review app, it looks like the graphs aren't appearing for the first example
image

**Comment by chriddyp** [comment]
> Looking at the review app, it looks like the graphs aren't appearing for the first example

Looks like it's intermittent. If I refresh, then it works 😕

**Comment by chriddyp** [comment]
image

The flow seems a little off here. Maybe just say "An alternative to providing CSS classes is to provide style dictionaries directly:"

**Comment by chriddyp** [comment]
Otherwise, the examples look really great! Thanks for cleaning these up, I think the community will really appreciate the expert CSS support here 💯

**Comment by chriddyp** [comment]
💃

**Pull request merged**
