### PR TITLE
[READY] Change code stylesheet based on Style guide

### PR DESCRIPTION
**Pull request by xhlulu**
The [Plotly Docs snippets](https://dash-gallery.plotly.host/python-docs-dash-snippets) currently use the proposed styling. Notably, the color of strings have a softer cyan-ish color.

The following colors were changed:
- background color: #F7FAFC
- comments color: #A1ACC3
- regular color: #3F4F75
- keyword, attribute, selector-tag, meta-keyword, doctag, name color: #20293D
- string, number, type, selector color: #60BAB6

Post-merge checklist:

The master branch is auto-deployed to `dash.plotly.com`.
Once you have merged your PR, wait 5-10 minutes and check dash.plotly.com
to verify that your changes have been made.

- [x] I understand

If this PR documents a new feature of Dash:

- [ ] Comment on the original Dash issue with a link to the new docs.
- [ ] Reply to any community thread(s) asking for this feature.

If this PR includes a new dataset available at a remote URL:
- [ ] I have added this dataset to the `datasets/` folder
- [ ] I have added a mapping between the remote URL and the filename in the
`datasets/` folder into the `find_and_replace` dict in `dash_docs/tools.py`

If this PR adds an image or animated GIF:
- [ ] This image was saved and referenced locally rather than via an external link

If I introduced a new relative link inside `dcc.Markdown`:
- [ ] I considered whether I could replace the `dcc.Markdown` call with `rc.Markdown`, which will replace relative links with `tools.relpath` internally. Otherwise, I used e.g. `<dccLink href=tools.relpath('/layout') children="the first chapter"/>` instead of `[the first chapter](/layout)` (importing `tools` from `dash_docs`), and set `dangerously_allow_html=true` in the `dcc.Markdown` call.

If I changed the `chapter_index` by removing or relocating a page:
- [ ] I added a redirect in `dash_docs/server.py` from the old URL to the new URL

### CODE REVIEW

**Comment by chriddyp** [comment]
My colorblind eyes have a pretty hard time with the low contrast between the background color and the strings:
image

**Comment by angeladaodao** [comment]
I can give a darker color for the strings

**Comment by angeladaodao** [comment]
Does any of those work for you? @chriddyp 

Option1:
Screen Shot 2020-11-16 at 3 24 43 PM

Option 2:
Screen Shot 2020-11-16 at 3 35 06 PM

Option 3:
Screen Shot 2020-11-16 at 3 10 26 PM

**Comment by chriddyp** [comment]
Option 1 & Option 2 look good!

**Comment by angeladaodao** [comment]
sounds good! will ask Xing to change the colors

**Comment by xhlulu** [comment]
I updated the file

**Comment by xhlulu** [comment]
I just added a new function color font and a new font, now it looks like this:
image

**Comment by angeladaodao** [comment]
Here are some function colors that @nicolaskruchten suggested, any preference? @chriddyp @nicolaskruchten 
Option 1:
Screen Shot 2020-11-16 at 5 06 35 PM

Option 2:
Screen Shot 2020-11-16 at 5 07 44 PM

Option 3:
Screen Shot 2020-11-16 at 5 08 14 PM

Option 4:
Screen Shot 2020-11-16 at 5 07 21 PM

Option 5:
Screen Shot 2020-11-16 at 5 10 54 PM

Option 6:
Screen Shot 2020-11-16 at 5 08 37 PM

Option 7:
Screen Shot 2020-11-16 at 5 10 35 PM

Option 8:
Screen Shot 2020-11-16 at 5 09 02 PM

Option 9:
Screen Shot 2020-11-16 at 5 09 31 PM

Option 10:
Screen Shot 2020-11-16 at 5 09 47 PM

Option 11:
Screen Shot 2020-11-16 at 5 10 15 PM

**Comment by chriddyp** [comment]
4, 6, & 8 have nice contrast to my eyes

**Comment by xhlulu** [comment]
@nicolaskruchten what's your preference between 4/6/8?

**Comment by nicolaskruchten** [comment]
4 is fine. Black would be fine too, it's not that important to me that there be high contrast here, I just think that bold red is too much :)

**Comment by xhlulu** [comment]
I updated the color to #636EFA

**Review by chriddyp — APPROVED** [review]
💃

**Pull request merged**
