### PR TITLE
Add dash-datashader to gallery

### PR DESCRIPTION
**Pull request by bcdunbar**
- adds dash-datashader to gallery.

### CODE REVIEW

**Comment by bcdunbar** [comment]
@jackparmer did you have a blurb in mind for this example or are you happy with "Visualize millions of points with Datashader and Plotly."?

**Comment by bcdunbar** [comment]
@plotly/dash - any takers for a quick review?

**Comment by bcdunbar** [comment]
@chriddyp following on from slack convo (few weeks ago), is this fine to merge now?

**Comment by jackparmer** [comment]
@bcdunbar yes please merge this

**Comment by bcdunbar** [comment]
closing in favor of https://github.com/plotly/dash-docs/pull/99

**Pull request closed without merging**
