### PR TITLE
redirects post-641

### PR DESCRIPTION
**Pull request by alexcjohnson**
A few redirects back to the URLs before #641 

@chriddyp @Marc-Andre-Rivet did I get these right? Any others?

I also added a partial fallback on missing urls - so if you go to `/datatable/something` and we don't find the whole thing, we'll at least take you to `/datatable` - seem reasonable?

### CODE REVIEW

**Comment by alexcjohnson** [comment]
hmm my partial redirect didn't work, investigating...

**Comment by Marc-Andre-Rivet** [comment]
`dash-entreprise` seems to be unable to find any subpath with either the correct path (https://dash-docs-pr-704.herokuapp.com/dash-enterprise/privacy) or the redirected path (https://dash-docs-pr-704.herokuapp.com/dash-deployment-server/privacy)

Behavior for table and DAQ seems fine though.

**Comment by alexcjohnson** [comment]
Fixed the dash-enterprise subsections - thanks @Marc-Andre-Rivet - anything else?

**Comment by alexcjohnson** [comment]
the `.PNG` file extensions are weird - I tried to simply rename them locally but git didn't pick it up as a change - had to rename them BACK to `.PNG`, then `git mv` them to `.png` - now AFAICT all the images in the DE section show up correctly.

**Comment by chriddyp** [comment]
💃

**Pull request merged**
