### PR TITLE
Dash Deployment Platform -> Dash Deployment Server

### PR DESCRIPTION
**Pull request by nicolaskruchten**

### CODE REVIEW

**Comment by nicolaskruchten** [comment]
@cldougl I did a bit more renaming here, hopefully that doesn't interfere with any work you're doing...

**Comment by cldougl** [comment]
@nicolaskruchten nope doesn't interfere

**Comment by nicolaskruchten** [comment]
@chriddyp sorry, I tacked on a few more changes, can you confirm your 💃 stands? :)

**Comment by nicolaskruchten** [comment]
@cldougl we'll need to get new screencaps of the DDS so they don't say "App Manager" and there are some `app-manager` strings here that I didn't touch...

**Pull request merged**
