### PR TITLE
fixes a couple of bugs in interactive vis

### PR DESCRIPTION
**Pull request by nicolaskruchten**
Post-merge checklist:

The master branch is auto-deployed to `dash.plot.ly`.
Once you have merged your PR, wait 5-10 minutes and check dash.plot.ly 
to verify that your changes have been made.

- [x] I understand

### CODE REVIEW

**Comment by nicolaskruchten** [comment]
Right now the country-indicator demos show 1952/1957 in the sliders but show blank plots because the `Value` field in the CSV is null for those years, but a trailing `.dropna()` fixes that.

In https://dash.plot.ly/interactive-graphing the slider accepts years that aren't in the dataset at all right now, resulting in broken-looking interactivity, and the `step=None` fixes that.

**Comment by alexcjohnson** [comment]
Something weird is going on here (which thankfully showed up in the percy diffs) - if I look at https://dash-docs-pr-709.herokuapp.com/getting-started-part-2 - specifically the "multiple inputs" graph 2/3 of the way down, the data look totally different from what they were before - and largely uncorrelated in the default view of life expectancy vs fertility rate, whereas previously there was a strong correlation.
Now:
Screen Shot 2019-11-22 at 10 11 56 AM

Previously:
Screen Shot 2019-11-22 at 10 12 49 AM

Are we doing something with the data that's incompatible with `dropna`?

**Comment by nicolaskruchten** [comment]
hmm nice catch. that is really weird, i'll dig into it.

**Comment by nicolaskruchten** [comment]
Well, this dataset is kind of whack:

image

**Comment by nicolaskruchten** [comment]
Basically there are many combinations of year/indicator1/indicator2 which will result in an empty plot. I think we should just switch to a much smaller, fully-populated dataset.

**Comment by nicolaskruchten** [comment]
OK I've created a new dataset with no indicators or years that have all-NaNs, but I've left all the NaNs in there, so nothing is out of order.

**Pull request merged**
