### PR TITLE
add phylogenetic project on Plotly Gallery

### PR DESCRIPTION
**Pull request by TahiriNadia**

### CODE REVIEW

**Comment by xhlulu** [comment]
I would recommend to work on the `TahiriNadia:dev` branch in the future, following the philosophy of never working on the master branch 👓 

http://scikit-learn.org/0.15/developers/index.html#how-to-contribute

**Comment by chriddyp** [comment]
is this ready to merge?

**Comment by TahiriNadia** [comment]
I think so, just I'm not sure for the gif image

**Comment by xhlulu** [comment]
💃 @TahiriNadia Please merge this PR if it's good now :)

**Comment by TahiriNadia** [comment]
:dancer:

**Pull request merged**
