### PR TITLE
apply relpath to chapter links so that TOC links work in dash enterprise docs

### PR DESCRIPTION
**Pull request by michaelbabyn**
resolves https://github.com/plotly/dash-enterprise-docs/issues/158

Post-merge checklist:

The master branch is auto-deployed to `dash.plot.ly`.
Once you have merged your PR, wait 5-10 minutes and check dash.plot.ly
to verify that your changes have been made.

- [ ] I understand

If this PR documents a new feature of Dash:

- [ ] Comment on the original Dash issue with a link to the new docs.
- [ ] Reply to any community thread(s) asking for this feature.

If this PR includes a new dataset available at a remote URL:
- [ ] I have added this dataset to the `datasets/` folder
- [ ] I have added a mapping between the remote URL and the filename in the
`datasets/` folder into the `find_and_replace` dict in `dash_docs/tools.py`

If I introduced a new relative link inside `dcc.Markdown`:
- [ ] I used e.g. `<dccLink href="/getting-started" children="the first chapter"/>` instead of `[the first chapter](/getting-started)`.

### CODE REVIEW

**Comment by chriddyp** [comment]
💃

**Comment by michaelbabyn** [comment]
@chriddyp , could you give me an approving review? I can't merge yet

**Comment by michaelbabyn** [comment]
[These tests](https://github.com/plotly/dash-docs/blob/2cf2a2ae775cb347e7ade2ebe66a5e59851191b1/.circleci/config.yml#L44) pass locally and this PR shouldn't change anything at all if `DASH_DOCS_URL_PREFIX` isn't set in the environment so I'm confused about why the tests are failing. The point of failure is consistently at `dash-bio/speck` though.

```
INFO     dash.testing.browser:browser.py:142 taking snapshot name => dash-bio/speck - py2.7
ERROR    dash.testing.browser:browser.py:132 snapshot at resource dash-bio/speck error
Traceback (most recent call last):
  File "/home/circleci/project/venv/src/dash/dash/testing/browser.py", line 124, in visit_and_snapshot
    self.percy_snapshot(path, wait_for_callbacks=wait_for_callbacks)
  File "/home/circleci/project/venv/src/dash/dash/testing/browser.py", line 148, in percy_snapshot
    until(self._wait_for_callbacks, timeout=40, poll=0.3)
  File "/home/circleci/project/venv/src/dash/dash/testing/wait.py", line 18, in until
    res = wait_cond()
  File "/home/circleci/project/venv/src/dash/dash/testing/dash_page.py", line 44, in _wait_for_callbacks
    if self.window_store:
  File "/home/circleci/project/venv/src/dash/dash/testing/dash_page.py", line 41, in window_store
    return self.driver.execute_script("return window.store")
  File "/home/circleci/project/venv/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "/home/circleci/project/venv/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/circleci/project/venv/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
TimeoutException: Message: timeout: Timed out receiving message from renderer: -0.001
  (Session info: chrome=80.0.3987.100)
```

**Comment by chriddyp** [comment]
Hm, that's odd. @Marc-Andre-Rivet - could you take a look?

**Comment by Marc-Andre-Rivet** [comment]
@chriddyp @michaelbabyn I did a sanity run against master and it failed in the same way this branch fails. The docker sha256 changed from 2 weeks ago from `da1f7...` to `35a58...`. I suspect that it used to be run against Chrome79 instead of 80 and something is up with that. More to come.

**Pull request merged**
