### PR TITLE
attempt hiding pagemenu for screenshot tests

### PR DESCRIPTION
**Pull request by chriddyp**
Post-merge checklist:

The master branch is auto-deployed to `dash.plot.ly`.
Once you have merged your PR, wait 5-10 minutes and check dash.plot.ly
to verify that your changes have been made.

- [x] I understand

If this PR documents a new feature of Dash:

- [ ] Comment on the original Dash issue with a link to the new docs.
- [ ] Reply to any community thread(s) asking for this feature.

If this PR includes a new dataset available at a remote URL:
- [ ] I have added this dataset to the `datasets/` folder
- [ ] I have added a mapping between the remote URL and the filename in the
`datasets/` folder into the `find_and_replace` dict in `dash_docs/tools.py`

If this PR adds an image or animated GIF:
- [ ] This image was saved and referenced locally rather than via an external link

If I introduced a new relative link inside `dcc.Markdown`:
- [ ] I considered whether I could replace the `dcc.Markdown` call with `reusable_components.Markdown`, which will replace relative links with `tools.relpath` internally. Otherwise, I used e.g. `<dccLink href=tools.relpath('/layout') children="the first chapter"/>` instead of `[the first chapter](/layout)` (importing `tools` from `dash_docs`), and set `dangerously_allow_html=true` in the `dcc.Markdown` call.

If I changed the `chapter_index` by removing or relocating a page:
- [ ] I added a redirect in `dash_docs/server.py` from the old URL to the new URL

### CODE REVIEW

**Comment by alexcjohnson** [comment]
This will solve the percy issue, without adding extra overhead of waiting for these menus to complete - which is fantastic 🎉

But it means we don't have any tests of the functionality of the page menu. Can we add a test that just loads one page, tests that the page menu becomes correct, then clicks a `dcc.Link` and tests that the correct new entries appear? Just hard-coding the entries for two pages that aren't expected to change often should suffice, I'd say.

**Comment by chriddyp** [comment]
Great idea @alexcjohnson  👍 

Added in the recent commits

**Comment by chriddyp** [comment]
There are still some diffs to be ignored in the bio examples, but I'd like to tackle that later given the number of changes made in https://github.com/plotly/dash-docs/pull/826. Once this PR is in, we'll have much more sane diffs to compare in https://github.com/plotly/dash-docs/pull/826.

**Comment by chriddyp** [comment]
alright, tests are passing @alexcjohnson !

**Pull request merged**
