### PR TITLE
Added all dashBio main page files and app component files.

### PR DESCRIPTION
**Pull request by HammadTheOne**
Post-merge checklist:

The master branch is auto-deployed to `dash.plot.ly`.
Once you have merged your PR, wait 5-10 minutes and check dash.plot.ly 
to verify that your changes have been made.

- [x] I understand

### CODE REVIEW

**Comment by alexcjohnson** [comment]
Don’t we gitignore `.RData` and `.Rhistory`? Do we need to add a pattern to ignore them in subdirectories? (Now that you’ve committed them you’ll *also* have to `git rm` them to get `git` to forget them)

**Comment by rpkyle** [comment]
> Don’t we gitignore `.RData` and `.Rhistory`? Do we need to add a pattern to ignore them in subdirectories? (Now that you’ve committed them you’ll _also_ have to `git rm` them to get `git` to forget them)

I'm not sure that we do, but we should. I've also added `.DS_Store`, don't think we want to commit that either. I can open a PR to make this change repo-wide.

**Comment by rpkyle** [comment]
Closes plotly/dash-bio#13105.

**Comment by rpkyle** [comment]
Nice work! :dancer:

**Pull request merged**
