### PR TITLE
[WIP] DashR Cytoscape docs

### PR DESCRIPTION
**Pull request by ohaanika**
Issue: plotly/streambed#13106

Following the [Python version of the docs](https://dash.plot.ly/cytoscape), these parts have been drafted, excluding the details below:

- [x] DashR Cytoscape home page
- [x] Part 1. Elements
- [x] Part 2. Layout
- [x] Part 3. Styling
- [x] Part 4. Dash Callbacks
- [x] Part 5. Event Callbacks for User Interactions
- [ ] Part 6. Cytoscape for Phylogeny Trees
- [x] Part 7. Component Reference

Details to be addressed:

- [ ] Need to recreate some demos equivalent to the [Python demos](https://github.com/plotly/dash-cytoscape/tree/master/demos) that are linked in the docs (e.g. see **Advanced usage of callbacks** in [Part 5 (Python version)](https://dash.plot.ly/cytoscape/events)). Should I also add these into the [dash-cytoscape repo](https://github.com/plotly/dash-cytoscape/) once they are complete? --> _commented out_
- [ ] Handle Phylogeny Trees as done using Biopython in the [Part 6 (Python version)](https://dash.plot.ly/cytoscape/biopython). --> _commented out link to section in contents page for now_
- [ ] Certain Cytoscape properties are mentioned in [Part 7 (Python version)](https://dash.plot.ly/cytoscape/reference) but not shown when using `props_to_list`.
- [ ] Should we include the extra layouts mentioned in [Part 2 (Python version)](https://dash.plot.ly/cytoscape/layout)? --> _commented out_

Details to be addressed when proofreading: 

- [ ] Ensure terminology matches R instead of Python 
- [ ] Ensure links point to R instead of Python files
- [ ] Remove mentions of Python libraries and replace with R package references if necessary/relevant

### CODE REVIEW

**Comment by ohaanika** [comment]
@rpkyle The following Cytoscape properties mentioned in the [Python version of **Part 7. Component Reference**](https://dash.plot.ly/cytoscape/reference) are not shown when using `props_to_list`:

- minZoom (number; optional)
- maxZoom (number; optional)
- zoomingEnabled (boolean; optional)
- userZoomingEnabled (boolean; optional)
- boxSelectionEnabled (boolean; optional)
- autoungrabify (boolean; optional)
- autolock (boolean; optional)
- autounselectify (boolean; optional)
- autoRefreshLayout (boolean; optional)
- tapNode (dict; optional)

**Comment by ohaanika** [comment]
@rpkyle On another note, when I use `props_to_list` function from the [utils.R](https://github.com/plotly/dash-docs/blob/dashr-squashed/dashr/utils.R) currently in the branch `dashr-squashed`, I output a table just fine.

However, when using the `propsToList` function addressed in #532, I get the following error message:
```
Error in eval(parse(text = example.ready.for.eval)) :
  attempt to apply non-function
Calls: source ... withVisible -> eval -> eval -> <Anonymous> -> eval -> eval
Execution halted
```

Just in case I'm making wrong assumptions as to how I should call the function, [here](https://github.com/plotly/dash-docs/blob/dashr-cytoscape/dashr/chapters/dash-cytoscape/reference/index.R) is how I call it.

**Comment by rpkyle** [comment]
> @rpkyle On another note, in case the `propsToList` function addressed in #532 is meant to be more updated than the `props_to_list` function from the [utils.R](https://github.com/plotly/dash-docs/blob/dashr-squashed/dashr/utils.R) currently in the branch `dashr-squashed`:

Ah, yes. I suggested we rename the function to make it camelCase instead of snake case, but that's deferred until post-release. I'll have another look at the repo this week and try to make this change.

**Comment by rpkyle** [comment]
> @rpkyle The following Cytoscape properties mentioned in the [Python version of **Part 7. Component Reference**](https://dash.plot.ly/cytoscape/reference) are not shown when using `props_to_list`:
> 
> * minZoom (number; optional)
> * maxZoom (number; optional)
> * zoomingEnabled (boolean; optional)
> * userZoomingEnabled (boolean; optional)
> * boxSelectionEnabled (boolean; optional)
> * autoungrabify (boolean; optional)
> * autolock (boolean; optional)
> * autounselectify (boolean; optional)
> * autoRefreshLayout (boolean; optional)
> * tapNode (dict; optional)
> * tapNodeData (dict; optional)
> * tapEdge (dict; optional)
> * tapEdgeData (dict; optional)
> * mouseoverNodeData (dict; optional)
> * mouseoverEdgeData (dict; optional)
> * selectedNodeData (list; optional)
> * selectedEdgeData (list; optional)
> 
> Will default values be indicated in a separated column or mentioned in the description?

Hmm, not sure what's going on there. I see them:

``
Argument 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   "maxZoom" 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 Description 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               "A maximum bound on the zoom level of the graph. The viewport can not be scaled larger than this zoom level." 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Type 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   "Numeric" 
``

**Pull request merged**
